# Generated by Django 5.0.3 on 2024-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bed', 'bed'), ('sofa', 'sofa'), ('table', 'table'), ('livingroom', 'livingroom'), ('bedroom', 'bedroom'), ('cupboard', 'cupboard')], max_length=20),
        ),
    ]
